# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks! :linkage => :static

target 'JGAlertDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JGAlertDemo
  pod 'JGAlert','~> 1.0.1'

end
